name: Quality

on:
  pull_request:
    branches:
      - main
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          file_patterns: "packages/.*/(src|package.json|tsconfig.json|clean-package.config.json|tsdown.config.ts),turbo.json,tsconfig.json"

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}

      - name: Install
        if: steps.check-modified.outputs.changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Build packages
        if: steps.check-modified.outputs.changed == 'true'
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          file_patterns: "packages/.*/(src|package.json|tsconfig.json|vitest.config.mts),scripts/setup-test.ts"

      - name: Install
        if: steps.check-modified.outputs.changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Run tests
        if: steps.check-modified.outputs.changed == 'true'
        run: pnpm test

      - name: Upload coverage
        if: steps.check-modified.outputs.changed == 'true'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          file: ./coverage/coverage-final.json
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          codecov_yml_path: ./codecov.yml

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          file_patterns: "packages/,.eslint/,eslint.config.ts,tsconfig.json"

      - name: Install
        if: steps.check-modified.outputs.changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Run lint
        if: steps.check-modified.outputs.changed == 'true'
        run: pnpm lint

  type_script:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          file_patterns: "packages/,scripts/,.eslint/,eslint.config.ts,tsconfig.json"

      - name: Install
        if: steps.check-modified.outputs.changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        if: steps.check-modified.outputs.changed == 'true'
        run: pnpm typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files
        id: check-modified
        uses: ./.github/composite-actions/check-modified-files
        with:
          file_patterns: "packages/,scripts/,.prettierrc.json,.prettierignore"

      - name: Install
        if: steps.check-modified.outputs.changed == 'true'
        uses: ./.github/composite-actions/install

      - name: Run format
        if: steps.check-modified.outputs.changed == 'true'
        run: pnpm format
